### ISSUE TITLE
Problem when cloning the repo

### ISSUE THREAD

**Issue by YaooXu** [mhmgad/ExFaKT#3] opened 2020-11-01 07:23 UTC
First, the URL of this command `clone with git clone --recurse-submodules https://github.molgen.mpg.de/gadelrab/ExFaK` is 404. Maybe you mean https://github.com/mhmgad/ExFaKT?

Second, when I run `git clone --recurse-submodules https://github.com/mhmgad/ExFaKT.git`, the git will report that
> fatal: remote error: upload-pack: not our ref e987fc409e3ac8d6709086fbd51c9c47455fb23b
Fetched in submodule path 'Utils', but it did not contain e987fc409e3ac8d6709086fbd51c9c47455fb23b. Direct fetching of that commit failed.

then I found that the URL of the submodule `Utils` is also invalid.

**Comment by mhmgad** [comment] 2020-11-02 16:06
Thank you for pointing out these problems!

The problem is fixed now! Please re-clone the repo. I have also updated the readme file

**Closed by mhmgad** 2020-11-02 16:06 UTC
Labels: bug
